Repository mcollovati/quarkus-hilla, pull requests merged in 2023-06, with the labels that each got.

#62 feat: upgrade to Hilla 2.x and Quarkus 3.x
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/DropLdcStatementMethodNode.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/TransferTypesPluginClassVisitor.java
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/HillaPushClient.java
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/ReactiveEndpointTest.java
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/ReactiveSecureEndpointTest.java
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/SpringReplacementsTest.java
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/endpoints/ReactiveSecureEndpoint.java
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/endpoints/SecureEndpoint.java
  hilla-shaded-deps/pom.xml
  integration-tests/smoke-tests/frontend/routes.ts
  integration-tests/smoke-tests/package-lock.json
  integration-tests/smoke-tests/package.json
  integration-tests/smoke-tests/src/main/java/com/example/application/ClockService.java
  integration-tests/smoke-tests/src/main/java/com/example/application/endpoints/helloworld/HelloWorldEndpoint.java
  integration-tests/smoke-tests/src/main/java/com/example/application/endpoints/helloworld/TestResource.java
  integration-tests/smoke-tests/src/main/java/com/example/application/endpoints/helloworld/UserInfoEndpoint.java
  integration-tests/smoke-tests/src/main/java/com/example/application/flow/FlowView.java
  integration-tests/smoke-tests/tsconfig.json
  pom.xml
  runtime/pom.xml
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaAtmosphereObjectFactory.java
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityPolicy.java
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusApplicationContext.java
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointController.java
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointControllerConfiguration.java
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointProperties.java
  runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusViewAccessChecker.java
Labels: format:checked

#95 chore(actions): run formatting check only for PRs
  .github/workflows/validation.yaml
Labels: format:checked

#97 test: run end to end tests in both development and production mode
  .github/workflows/validation.yaml
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/endpoints/ReactiveEndpoint.java
  integration-tests/smoke-tests/pom.xml
  integration-tests/smoke-tests/src/test/java/com/example/application/BootstrapTest.java
  pom.xml
Labels: format:checked

#98 cherry-pick: PR 95 and 97 into 1.0
  .github/workflows/validation.yaml
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/endpoints/ReactiveEndpoint.java
  integration-tests/smoke-tests/pom.xml
  integration-tests/smoke-tests/src/test/java/com/example/application/BootstrapTest.java
  pom.xml
Labels: format:checked

#99 chore(actions): add branch 1.0 to validation workflow push event
  .github/workflows/validation.yaml
Labels: format:checked

#101 chore(actions): activate required profile for release build
  .github/workflows/release.yaml
Labels: format:checked

#106 chore: add link to starter project
  README.md
Labels: format:checked

#111 chore(actions): set ignore paths for validation workflow
  .github/workflows/validation.yaml
Labels: format:checked

#113 chore: add license and version badges to README
  README.md
Labels: format:checked

#112 chore: add license and version badges to README
  README.md
Labels: format:checked

#119 fix(actions): skip validation check for ignored paths
  .github/workflows/validation-not-required.yaml
Labels: format:checked

#120 fix(actions): skip validation check for ignored paths (#119) (CP: 1.0)
  .github/workflows/validation-not-required.yaml
Labels: format:checked, cherry-pick

#122 chore(actions): add formatting check workflow
  .github/scripts/format-check-report.tpl.md
  .github/workflows/formatting-check.yaml
  .github/workflows/validation.yaml
Labels: format:checked

#125 chore(actions): parallelize test execution
  .github/workflows/validation-not-required.yaml
  .github/workflows/validation.yaml
Labels: format:checked

#130 chore(actions): parallelize test execution (#125) (CP: 1.0)
  .github/workflows/validation-not-required.yaml
  .github/workflows/validation.yaml
Labels: cherry-pick

#128 chore: add compatibility matrix
  README.md
Labels: format:checked

#129 chore: add compatibility matrix (CP: 1.0)
  README.md
Labels: format:checked

#131 fix: fix urls in flattened POM files
  pom.xml
Labels: format:checked

#132 fix: fix urls in flattened POM files (#131) (CP: 1.0)
  pom.xml
Labels: format:checked
