Repository mcollovati/quarkus-hilla, pull requests merged in 2023-11, with the labels that each got.

#378 chore(actions): disable chrome install based on repository variable (CP: 1.0)
  .github/workflows/validation.yaml
Labels: cherry-pick

#310 chore: update compatibility matrix
  README.md
Labels: format:checked

#391 refactor: Refactor bytecode manipulation
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/AsmUtils.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/DropInitStatementMethodNode.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/DropLdcStatementMethodNode.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/DropStatementMethodNode.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/MethodRedirectNode.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/MethodRedirectVisitor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/MethodReplacementClassVisitor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/MethodSignature.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/NonnullPluginConfigClassVisitor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/NonnullPluginConfigProcessorClassVisitor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/PushEndpointClassVisitor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/SpringReplacementsRedirectMethodVisitor.java
  deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/SpringReplacer.java
Labels: format:checked, internal-improvement, byte-code hack

#394 chore: bump project and Hilla to 2.4
  .github/dependabot.yml
  .github/workflows/release.yaml
  .github/workflows/update-npm-deps.yaml
  .github/workflows/validation-nightly.yaml
  .github/workflows/validation.yaml
  README.md
  integration-tests/hybrid-smoke-tests/package-lock.json
  integration-tests/hybrid-smoke-tests/package.json
  integration-tests/panache-extension-support-test/package-lock.json
  integration-tests/panache-extension-support-test/package.json
  integration-tests/react-smoke-test/package-lock.json
  integration-tests/react-smoke-test/package.json
  integration-tests/smoke-tests/package-lock.json
  integration-tests/smoke-tests/package.json
  integration-tests/spring-extension-support-test/package-lock.json
  integration-tests/spring-extension-support-test/package.json
  pom.xml
Labels: format:checked

#398 chore(actions): add rules for hilla version upgrade detection
  etc/release-version-rules.xml
Labels: format:checked, target/1.0, target/2.2, target/2.0, target/2.1, target/2.3

#412 test: open dev tools to show errors
  integration-tests/test-commons/src/main/java/com/github/mcollovati/quarkus/testing/AbstractTest.java
Labels: format:checked

#413 chore(actions): collect outputs for failed snapshot validation
  .github/actions/run-validation/action.yaml
Labels: format:checked

#415 test: open dev tools to show errors (#412) (CP: 2.2)
  integration-tests/test-commons/src/main/java/com/github/mcollovati/quarkus/testing/AbstractTest.java
Labels: format:checked, cherry-pick

#418 chore(actions): disable chrome install based on repository variable (#377) (CP: 2.1)
  .github/actions/run-validation/action.yaml
  .github/workflows/quarkus-snapshot.yaml
  .github/workflows/validation.yaml
Labels: cherry-pick

#416 test: open dev tools to show errors (#412) (CP: 2.1)
  integration-tests/hybrid-smoke-tests/src/test/java/com/github/mcollovati/quarkus/testing/AbstractTest.java
Labels: format:checked, cherry-pick

#419 test: fix react tests
  integration-tests/panache-extension-support-test/src/test/java/com/example/application/SmokeTest.java
  integration-tests/spring-extension-support-test/src/test/java/com/example/application/SmokeTest.java
Labels: format:checked, target/2.3

#392 chore: add link to JReleaser
  README.md
Labels: format:checked

#430 fix: exclude spring-boot dependencies from hilla artifact
  hilla-jandex/pom.xml
Labels: format:checked

#433 fix: support Atmosphere heartbeat in HillaPushClient
  deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/HillaPushClient.java
Labels: format:checked
