Repository mcollovati/quarkus-hilla, pull requests merged in 2025-01, with the labels that each got.

#1171 feat: run Vaadin plugin as build step
  .github/workflows/validation.yaml
  README.md
  commons/aot-browser-finder-callable-workaround/pom.xml
  commons/aot-browser-finder-callable-workaround/src/main/java/com/vaadin/hilla/engine/AotBrowserCallableFinder.java
  commons/deployment/pom.xml
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/OffendingMethodCallsReplacer.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/vaadinplugin/QuarkusHillaBrowserCallableFinder.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/vaadinplugin/QuarkusPluginAdapter.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/vaadinplugin/VaadinBuildTimeConfig.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/vaadinplugin/VaadinPlugin.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/vaadinplugin/VaadinPrepareFrontendTask.java
  commons/deployment/src/main/resources/META-INF/services/io.quarkus.deployment.CodeGenProvider
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaReplacements.java
  integration-tests/pom.xml
  pom.xml
Labels: format:checked

#1199 fix: apply non null plugin patch to the correct class
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/OffendingMethodCallsReplacer.java
Labels: format:checked, target/24.4, target/24.5, target/24.6

#1200 fix: apply non null plugin patch to the correct class (#1199) (CP: 24.6)
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/OffendingMethodCallsReplacer.java
Labels: format:checked, cherry-pick

#1201 fix: apply non null plugin patch to the correct class (#1199) (CP: 24.5)
  deployment-commons/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/OffendingMethodCallsReplacer.java
Labels: format:checked, cherry-pick

#1202 fix: apply non null plugin patch to the correct class (#1199) (CP: 24.4)
  deployment-commons/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/SpringReplacer.java
Labels: format:checked, cherry-pick

#1036 feat: add dev ui
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/HillaSecurityBuildItem.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/AccessAnnotationInfo.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/EndpointBuildItem.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/EndpointInfo.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/MethodDescriptor.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/ParameterInfo.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/QuarkusHillaDevUICommonsProcessor.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/devui/TypeInfo.java
  commons/deployment/src/main/resources/dev-ui/qwc-quarkus-hilla-browser-callables.js
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityPolicy.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityRecorder.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointConfiguration.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusHandlerHelper.java
  commons/runtime/src/main/resources/META-INF/quarkus-extension.yaml
  integration-tests/smoke-tests/src/main/java/com/example/application/endpoints/helloworld/HelloWorldEndpoint.java
  lit/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/devui/QuarkusHillaDevUIProcessor.java
  lit/deployment/src/main/resources/dev-ui/qwc-quarkus-hilla.js
  lit/runtime/src/main/resources/META-INF/quarkus-extension.yaml
  react/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/devui/QuarkusHillaDevUIProcessor.java
  react/deployment/src/main/resources/dev-ui/qwc-quarkus-hilla-react.js
  react/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Labels: format:checked

#1232 fix: partially revert "feat: add dev ui"
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/AuthFormBuildItem.java
  commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityPolicy.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityRecorder.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointConfiguration.java
  commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusHandlerHelper.java
  integration-tests/smoke-tests/src/main/java/com/example/application/endpoints/helloworld/HelloWorldEndpoint.java
Labels: format:checked

#1247 chore: drop support for unmaintained Hilla version
  .github/dependabot.yml
  .github/workflows/release.yaml
  .github/workflows/update-npm-deps.yaml
  .github/workflows/validation-nightly.yaml
  .github/workflows/validation.yaml
Labels: format:checked
